name: 'Mirror to Radicle'
description: 'A GitHub Action that mirrors your code to the Radicle peer-to-peer code hosting network.'
inputs:
  radicle-identity-passphrase:
    description: 'The passphrase you used when creating the Radicle identity keypair. (When you ran `rad auth`) '
    required: true
    default: ''
  radicle-identity-alias:
    description: 'An alias for your Radicle identity. Used to indicate what this key is used for.'
    required: true
    default: ''
  radicle-identity-private-key:
    description: 'The private key for the _machine account_ you created for GitHub Actions to use, in order to sign and push code from GitHub -> Radicle.'
    required: true
    default: ''
  radicle-identity-public-key:
    description: 'The private key for the _machine account_ you created for GitHub Actions to use, in order to sign and push code from GitHub -> Radicle.'
    required: true
    default: ''
  radicle-repository-id:
    description: 'The `repository id` of the repository you created on Radicle, when you ran `rad init`. You can find the repo id by switching to the folder of your radicle project and running `rad .`.'
    required: true
    default: ''
  radicle-project-name:
    description: 'The `xyz.radicle.project.name` found in your repository payload. You can see this by switching to the folder of your radicle project and running `rad inspect --payload`'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Install radicle-cli
      env:
        RAD_HOME: ${{ github.workspace }}/.radicle
      shell: bash
      run: |
        curl --show-error --silent --fail https://radicle.xyz/install | sh
        echo "RAD_HOME=${{ github.workspace }}/.radicle" >> $GITHUB_ENV
        echo "RAD_PASSPHRASE=${{ inputs.radicle-identity-passphrase }}" >> $GITHUB_ENV
        echo "${RAD_HOME}/bin" >> $GITHUB_PATH

    - name: Install helper packages
      shell: bash
      run: |
        sudo apt-get -y install socat

    - name: Setup Radicle Identity & Node
      shell: bash
      run: |          
        echo "Home: $HOME"
        rad --version          
        rad config init --alias "${{ inputs.radicle-identity-alias}}"
        echo "${{ inputs.radicle-identity-private-key }}" | base64 --decode > ${{ github.workspace }}/.radicle/keys/radicle
        echo "${{ inputs.radicle-identity-public-key }}" | base64 --decode > ${{ github.workspace }}/.radicle/keys/radicle.pub
        rad auth 

    - name: Start Radicle Node
      shell: bash
      run: |          
        rad config unset preferredSeeds
        rad config 
        
        rad node start
        
        echo "Waiting for node to start"
        max_retry=30
        counter=0
        until echo '{"command": "sessions"}' | socat - UNIX-CONNECT:${{ github.workspace }}/.radicle/node/control.sock
        do
           sleep 1
           [[ counter -eq $max_retry ]] && echo "Failed" && break 
           echo "Waiting for node to start... $counter"
           counter=$((counter+1))
        done

    - name: Wait for Node to connect to peers
      shell: bash
      run: |          
        max_retry=30
        counter=0
        until echo '{"command": "sessions"}' | socat - UNIX-CONNECT:${{ github.workspace }}/.radicle/node/control.sock | grep '"state":{"connected"'
        do
           sleep 1
           [[ counter -eq $max_retry ]] && echo "Failed" && break 
           echo "Waiting for node to connect... $counter"
           counter=$((counter+1))
        done
        
        rad node status



    - name: Clone from Radicle
      shell: bash
      run: |
        rad clone "${{ inputs.radicle-repository-id }}" --no-confirm --timeout 180

    - name: Fetch code from GitHub
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.radicle-project-name }}
      run: |
        
        export GH_REPO_URL=$( echo "${{ github.repositoryUrl }}" \
          | sed -e 's/git:\/\//https:\/\//g'
        )

        git remote add github ${GH_REPO_URL}
        git remote -v
        git fetch --all
        git checkout -b ${{ github.ref_name }} --track github/${{ github.ref_name }}
        

    - name: Push to Radicle Network
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.radicle-project-name }}
      run: |
        git push --force rad ${{ github.ref_name }}
        
        echo "Ensuring sync with the network"
        rad sync --announce --timeout 180
        
        rad node stop

